---
- name: ansible fqcn test playbook
  hosts: localhost
  gather_facts: true
  vars:
    xyz: abc
    num: 1
    deploy: true
    domain: example.com
  tasks:
    - name: test task 1
      command: cat dog

    - name: test task 2
      command:
        cmd: cat dog

    - name: test task 1 fqcn
      ansible.builtin.command: cat dog

    - name: test task 2 fqcn
      ansible.builtin.command:
        cmd: cat dog

    - name: assert
      assert:
        that: true
    - assert:
        that: not false

- name: roles
  collections:
    - 'debops.debops'
    - 'debops.roles01'
    - 'debops.roles02'
    - 'debops.roles03'
  roles:
    - role: bootstrap
      tags:
        - bootstrap
    - role: common
      tags:
        - common

---
# just tasks list

# named task
- name: test apt unnamed
  apt:
    name: ipsum

# named task w/ group as pitfall
- name: test copy with group as pitfall
  copy:
    content: aaa
    dest: xyz
    group: lorem

# galaxy module
- name: general command os6_config
  os6_config:
    commands: "{{ dellos_general_command | default([]) }}"
  when: ansible_network_os == "dellemc.os6.os6"

# this will be ignored due to cfg
- name: general command os10_config
  os10_config:
    commands: "{{ dellos_general_command | default([]) }}"

# unnamed task
- file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent
  when: "'ox' in group_names"

# unnamed fqcn
- ansible.builtin.copy:
    src: a
    dest: b

# named fqcn
- name: lorem ipsum
  ansible.builtin.copy:
    src: lorem
    dest: ipsum

# issue #11 check double colon
- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
  with_items:
    - "{{ inventory_hostname_short }}"
    - 127.0.0.1
    - ::1
  ignore_errors: true
  run_once: true

# block
- name: "configure ..."
  block:
    - name: "read ..."
      command: cat dog
      become: true
      check_mode: false
      changed_when: false
      register: _local_json

    - name: read json
      set_fact:
        current_of_local_json: "{{ _local_json.stdout | from_json }}"

    - name: "write {{ of_default_config }}"
      ansible.builtin.copy:
        dest: "{{ of_default_config }}"
        content: "{{ current_of_local_json | combine(of_local_json, recursive=true) | to_nice_json(indent=2, sort_keys=false) }}\n"
      notify: restart-xyz
  when: of_local_json

- name: test user ... expect buildin
  user:
    name: test
    password: '!'

- name: test issue 18
  command: echo "expect no openstack.cloud.config:system:set here"
  with_items:
    - app:disable dashboard
    - config:system:set a b
    - no:such:xxx

- name: test issue 22 - systemd
  systemd:
    name: systemd-timesyncd
    enabled: false
    state: stopped
    masked: true
- name: test issue 22 - systemd_service
  systemd_service:
    name: systemd-timesyncd
    enabled: false
    state: stopped
    masked: true

---
# issue #31
- name: test file 1
  file:
    path: /a/b/c/1

- name: command with vars 1
  command: echo "before file 2"
  vars:
    ansible_ssh_pipelining: true

- name: test file 2
  file:
    path: /a/b/c/2

- name: command with vars 2
  vars:
    ansible_ssh_pipelining: true
  command: echo "before file 3"

- name: test file 3
  file:
    path: /a/b/c/3
# end issue #31
