# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu
---
name: rebuild map
on:
  pull_request:
    paths: '*.py'
  push:
    paths: '*.py'
  schedule:
    - cron: "20 5 * * 5"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: install pyyaml
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: rebuild fqcn map
        run: |
          ./fqcn-fixer.py -f example.yml -u
